Use underscores in parameter names instead of dashes

diff --git a/components/tekton/tasks/base/argocd-sync-and-wait-task.yaml b/components/tekton/tasks/base/argocd-sync-and-wait-task.yaml
--- a/components/tekton/tasks/base/argocd-sync-and-wait-task.yaml
+++ b/components/tekton/tasks/base/argocd-sync-and-wait-task.yaml
@@ -22,12 +22,12 @@ spec:
       description: name of the deployment
     - name: namespace
       description: namespace where the deployment is located
-    - name: image-tag
+    - name: image_tag
       description: tag of the image that is expected to be deployed
     - name: container
       description: the ordinal position in the container (0,1,2) in .spec.template.spec.containers
       default: "0"
-    - name: application-name
+    - name: application_name
       description: name of the application to sync
     - name: revision
       description: the revision to sync to
@@ -54,33 +54,33 @@ spec:
         fi
         # Refresh application first
         echo "#### Refreshing application ####"
-        argocd app get "$(params.application-name)" --refresh "$(params.flags)"
+        argocd app get "$(params.application_name)" --refresh "$(params.flags)"
 
         # Application may already be syncing due to webhook
         echo "#### Waiting for automatic sync if it was already triggered (or other pending operation) ####"
-        argocd app wait "$(params.application-name)" --operation "$(params.flags)"
+        argocd app wait "$(params.application_name)" --operation "$(params.flags)"
 
         echo "#### Checking current tag in namespace $(params.namespace) ####"
         CURRENT_TAG=$(oc get deploy $(params.deployment) -n $(params.namespace) -o jsonpath="{.spec.template.spec.containers[$(params.container)].image}" | cut -d ":" -f2)
-        if [ "$CURRENT_TAG" = "$(params.image-tag)" ]; then
+        if [ "$CURRENT_TAG" = "$(params.image_tag)" ]; then
           echo "Image has been synced, exiting"
           exit 0
         fi
 
         echo "#### Running argocd sync... ####"
         EXIT_CODE=0
-        argocd app sync "$(params.application-name)" --revision "$(params.revision)" "$(params.flags)" || EXIT_CODE=$?
+        argocd app sync "$(params.application_name)" --revision "$(params.revision)" "$(params.flags)" || EXIT_CODE=$?
 
         echo "#### Waiting for argocd sync... ####"
-        argocd app wait "$(params.application-name)" --health "$(params.flags)"
+        argocd app wait "$(params.application_name)" --health "$(params.flags)"
 
         echo "#### Checking that rollout is finished ####"
         oc rollout status deploy $(params.deployment) -n $(params.namespace)
 
         CURRENT_TAG=$(oc get deploy $(params.deployment) -n $(params.namespace) -o jsonpath="{.spec.template.spec.containers[$(params.container)].image}" | cut -d ":" -f2)
-        if [ "$CURRENT_TAG" = "$(params.image-tag)" ]; then
+        if [ "$CURRENT_TAG" = "$(params.image_tag)" ]; then
           echo "#### Image has been synced ####"
         else
-          echo "#### Image failed to sync, requested tag is $(params.image-tag) but current tag is $CURRENT_TAG ####"
+          echo "#### Image failed to sync, requested tag is $(params.image_tag) but current tag is $CURRENT_TAG ####"
           exit 1;
         fi
